# Generated by Django 3.0.5 on 2020-04-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=50, unique=True)),
                ('nome', models.CharField(max_length=50)),
                ('preco', models.CharField(blank=True, max_length=50)),
                ('qtd', models.IntegerField(blank=True)),
            ],
        ),
    ]
